### PR TITLE
Added RR2 broadcast support

### PR DESCRIPTION
**Pull request by SerafimArts**
Minor Fixes:
1) Fixed timer types (NodeJS.Timeout instead of number)
2) Fixed SFSocket constructor option key duplications (i.e. `port`)

Features:
1) Actualized protocol (using `command` key instead of `topic`)

### CODE REVIEW

**Comment by AndrewKirkovski** [comment]
Tests are failing on this branch
image

**Comment by AndrewKirkovski** [comment]
Did `yarn add -D @types/node`, tests still failing after that

**Comment by AndrewKirkovski** [comment]
@SerafimArts

**Comment by SerafimArts** [comment]
@AndrewKirkovski Perhaps this is an old version of the TS. The static analyzer tells me that this type should be there, and if return the old one (it seems there was a `number`), the compiler will output warnings.

What should be there instead?

**Comment by AndrewKirkovski** [comment]
There is `yarn.lock` file there, so you should have specific installed by `yarn`

```
typescript@^3.6.4:
  version "3.7.5"
```

Don't use npm, `yarn` is listed in pre-requisites for development

@SerafimArts

**Pull request merged**
